version: '3'

services:
    mirotalksfu:
        image: mirotalksfu:latest
        build:
            context: .
            dockerfile: Dockerfile
        container_name: mirotalksfu
        hostname: mirotalksfu
        restart: unless-stopped
        ports:
            - '3000:3000/tcp'
            - '40000-40100:40000-40100/tcp'
            - '40000-40100:40000-40100/udp'
